---
- hosts: webserver
  become: yes
  become_user: root
  gather_facts: false
  tasks:
    - name: create a new group
      group:
        name: admin
        state: present
        local: 'groupdel'