---
- hosts: new_dc_webserver
  become: yes
  become_user: root
  tasks:

#    - name: take a backup on the new server
#      copy:
#        src: /etc/httpd/httpd.config
#        backup: yes

    - name: Transfer file from old data center to new data center
      synchronize:
        src : /opt/demofile.txt #this is the path on old dc webserver
        dest: /opt/demofile.txt #this is the path on the new dc webserver
      delegate_to: local