---
- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
    - name:               Create VPC
      ec2_vpc_net:
        name:             "{{ vpc_name }}"
        cidr_block:       "{{ vpc_cidr_block }}"
        region:           "{{ aws_region }}"
        state:            "present"
      register: my_vpc