---
- hosts: "new_dc_webserver, old_dc_webserver"
  become: yes
  become_user: root
  gather_facts: false
  tasks:
#    - name: create users
#      user:
#        name: "{{ item }}"
#        create_home: yes
#        generate_ssh_key: yes
#        ssh_key_bits: 2048
#        ssh_keys_file: .ssh/id_rsa
#        shell: /bin/bash
#      loop:
#        - sysadmin1
#        - sysadmin2
#        - developer1
#        - developer2
#/to create a new group and add users to the group, host module requires groupadd, groupdel, groupmod modules
#    - name: import playbook to create new groups
#      import_playbook: createnewgroup.yml
    - name: create a new group
      group:
        name: ansible
        state: present
        name: ansible
        state: present

    - name: create several users and assign them to appropriate groups
      user:
        name: ansile
        create_home: yes
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_keys_file: .ssh/id_rsa
        state: present
        groups: ansible"
#      loop:
#        - { name: 'sysadmin1', groups: 'admin'}
#        - { name: 'sysadmin2', groups: 'admin'}
#        - { name: 'developer1', groups: 'dev'}
#        - { name: 'developer2', groups: 'dev'}
#        - sysadmin1
#        - sysadmin2
#        - developer1
#        - developer2

#    - name: Check if 'wheel' group exists
#      group:
#        name: wheel
#        state: present
#
#    - name: allow 'wheel' group to ahve passwordless sudo
#      lineinfile:
#        dest: /etc/sudoers
#        state: present
#        regexp: '^%wheel'
#        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#        validate: 'visudo -cf %s'

#    - name: add sudoers users to wheel group
#      user:
#        name: "{{ item }}"
#        groups: wheel
#        append: yes
#        state: present
#
#      loop:
#        - sysadmin1
#        - sysadmin2
#        - developer1
#        - developer2

#    - name: loop through users
#      loop:
#        - sysadmin1
#        - sysadmin2
#        - developer1
#        - developer2

#    - name: Add the user 'sysadmin1' associated with group of 'admin'
#
#      user:
#        name: sysadmin1
#        create_home:  yes
#        groups: admin
#        generate_ssh_key: yes
#        ssh_key_bits: 2048
#        ssh_keys_file: .ssh/id_rsa
#        shell: /bin/bash
#
#
#    - name: Add the user 'sysadmin2' associated with group of 'admin'
#      user:
#        name: sysadmin2
#        create_home:  yes
#        groups: admin
#        generate_ssh_key: yes
#        ssh_key_bits: 2048
#        ssh_keys_file: .ssh/id_rsa
#        shell: /bin/bash
#
#    - name: Add the user 'sysadmin1' associated with group of 'admin'
#      user:
#        name: "{{ item }}"
#        create_home:  yes
#        groups: admin
#        generate_ssh_key: yes
#        ssh_key_bits: 2048
#        ssh_keys_file: .ssh/id_rsa
#        shell: /bin/bash

