---
- hosts: webserver
  connection: local
  gather_facts: false
  tasks:
    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      user:
        name: johnd
        comment: John Doe
