---
- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
    - name: creating my VPC template
      ec2_vpc_net:
        name: "Module_dev2"
        cidr_block: "10.10.0.0/16"
        region: "us-east-2"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        state: "present"
      register: create_vpc